apiVersion: apps/v1
kind: Deployment
metadata:
  name: chase-deploy
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: my-app
          image: ghcr.io/clee231/pipeline4all-practice-24:latest
          ports:
            - containerPort: 3000
