apiVersion: apps/v1
kind: Deployment
metadata:
  name: practice-deploy
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: my-app
        image: ghcr.io/clee231/slalom-pipeline-practice-24:latest
        ports:
        - containerPort: 3000
