apiVersion: apps/v1
kind: Deployment
metadata:
  name: chase-deploy
  labels:
    app: chase-me
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chase-me
  template:
    metadata:
      labels:
        app: chase-me
    spec:
      containers:
        - name: my-app
          image: ghcr.io/clee231/pipeline4all-practice-24:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: chase-deploy-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: chase-me
